### ISSUE TITLE
Split files per lecture

### ISSUE THREAD

**Issue by pirroh** [ADAEPFL/Notes#4]
It might help to come up with a proper directory structure -- i.e., one `.tex` file per lecture, possibly with an associated subdir for the images -- so that it will be easier to accept Pull Requests (fewer conflicts), and to edit the lecture notes per se once we approach the end of the course (otherwise we will end up with a giant `.tex` file).

**Comment by jmuth** [comment]
Yes you're right. I will restructure this way. Are [these convention](https://en.wikibooks.org/wiki/LaTeX/Modular_Documents) ok to be followed ?

**Comment by pirroh** [comment]
Yep, that's *the right way* :)

**Comment by glederrey** [comment]
@pirroh Can you check if it's what you wanted? If it's the case, we'll close this issue..

**Comment by pirroh** [comment]
LGTM!
