### ISSUE TITLE
Figure 5.3

### ISSUE THREAD

**Issue by timozattol** [ADAEPFL/Notes#5]
Thanks for the notes :+1: 

Seems to me like there's a small inversion of the PDF and CDF on figure 5.3 :)

**Comment by jmuth** [comment]
Aaaaaaand... That's right 😉 Thanks for the observation!

**Comment by timozattol** [comment]
Similar problem in figure 8.5 between Uniform & Random spammer :)

**Comment by jmuth** [comment]
In this case I don't agree. 
A **uniform spammer** always gives the same answer (let's say: *yes*).
On the x *yes*-documents, spammer finds them all.
On the y *no*-documents, spammer misses them all.

So he has a true pos. rate of 1 and a true neg. rate of 0.
(Opposite for uniform spammer giving *no*)

**Random spammer** gives random answer (let's say 50% *yes* and 50% *no*). For a corpus equally distributed he will classify 50% of the documents correctly, thus having both true-pos and true-rate at 0.5.

**Comment by timozattol** [comment]
@jmuth Oh sorry, I thought it was Figure 8.5 but it is not part of Figure 8.5, I was talking about the table just above Figure 8.5.

It says:
>Uniform spammer : gives
>random answers to any question
>Random spammer : keeps
>the same answer to every
>question

**Comment by jmuth** [comment]
OK this time I agree 😂
Thanks for reviewing. Please keep sharing the mistakes you notice.
